// 自动生成：stub 函数签名表（来源：SDL3 真实头文件）
// void SDL_CloseGamepad(SDL_Gamepad *gamepad)
// void SDL_CloseHaptic(SDL_Haptic *haptic)
// void SDL_CloseJoystick(SDL_Joystick *joystick)
// SDL_HapticEffectID SDL_CreateHapticEffect(SDL_Haptic *haptic, const SDL_HapticEffect *effect)
// void SDL_DestroyAudioStream(SDL_AudioStream *stream)
// void SDL_DestroyHapticEffect(SDL_Haptic *haptic, SDL_HapticEffectID effect)
// bool SDL_GetAudioDeviceFormat(SDL_AudioDeviceID devid, SDL_AudioSpec *spec, int *sample_frames)
// SDL_AudioDeviceID SDL_GetAudioStreamDevice(SDL_AudioStream *stream)
// bool SDL_GetBooleanProperty(SDL_PropertiesID props, const char *name, bool default_value)
// const char * SDL_GetError(void)
// SDL_GamepadBinding ** SDL_GetGamepadBindings(SDL_Gamepad *gamepad, int *count)
// SDL_GamepadButtonLabel SDL_GetGamepadButtonLabel(SDL_Gamepad *gamepad, SDL_GamepadButton button)
// SDL_Joystick * SDL_GetGamepadJoystick(SDL_Gamepad *gamepad)
// char ** SDL_GetGamepadMappings(int *count)
// const char * SDL_GetGamepadName(SDL_Gamepad *gamepad)
// int SDL_GetGamepadPlayerIndex(SDL_Gamepad *gamepad)
// SDL_PropertiesID SDL_GetGamepadProperties(SDL_Gamepad *gamepad)
// Uint32 SDL_GetHapticFeatures(SDL_Haptic *haptic)
// SDL_JoystickID SDL_GetJoystickID(SDL_Joystick *joystick)
// const char * SDL_GetJoystickName(SDL_Joystick *joystick)
// int SDL_GetJoystickPlayerIndex(SDL_Joystick *joystick)
// int SDL_GetNumJoystickAxes(SDL_Joystick *joystick)
// int SDL_GetNumJoystickButtons(SDL_Joystick *joystick)
// int SDL_GetNumJoystickHats(SDL_Joystick *joystick)
// SDL_GamepadType SDL_GetRealGamepadType(SDL_Gamepad *gamepad)
// bool SDL_HapticRumbleSupported(SDL_Haptic *haptic)
// bool SDL_InitHapticRumble(SDL_Haptic *haptic)
// bool SDL_InitSubSystem(SDL_InitFlags flags)
// bool SDL_IsGamepad(SDL_JoystickID instance_id)
// SDL_AudioStream * SDL_OpenAudioDeviceStream(SDL_AudioDeviceID devid, const SDL_AudioSpec *spec, SDL_AudioStreamCallback callback, void *userdata)
// SDL_Gamepad * SDL_OpenGamepad(SDL_JoystickID instance_id)
// SDL_Haptic * SDL_OpenHapticFromJoystick(SDL_Joystick *joystick)
// SDL_Joystick * SDL_OpenJoystick(SDL_JoystickID instance_id)
// bool SDL_PauseAudioDevice(SDL_AudioDeviceID devid)
// bool SDL_PlayHapticRumble(SDL_Haptic *haptic, float strength, Uint32 length)
// bool SDL_PollEvent(SDL_Event *event)
// bool SDL_PutAudioStreamData(SDL_AudioStream *stream, const void *buf, int len)
// void SDL_QuitSubSystem(SDL_InitFlags flags)
// bool SDL_ResumeAudioDevice(SDL_AudioDeviceID devid)
// bool SDL_RumbleGamepad(SDL_Gamepad *gamepad, Uint16 low_frequency_rumble, Uint16 high_frequency_rumble, Uint32 duration_ms)
// bool SDL_RunHapticEffect(SDL_Haptic *haptic, SDL_HapticEffectID effect, Uint32 iterations)
// bool SDL_SetGamepadLED(SDL_Gamepad *gamepad, Uint8 red, Uint8 green, Uint8 blue)
// bool SDL_SetHapticAutocenter(SDL_Haptic *haptic, int autocenter)
// bool SDL_SetHint(const char *name, const char *value)
// void SDL_SetLogOutputFunction(SDL_LogOutputFunction callback, void *userdata)
// void SDL_SetLogPriorities(SDL_LogPriority priority)
// bool SDL_StopHapticEffect(SDL_Haptic *haptic, SDL_HapticEffectID effect)
// bool SDL_StopHapticRumble(SDL_Haptic *haptic)
// bool SDL_UpdateHapticEffect(SDL_Haptic *haptic, SDL_HapticEffectID effect, const SDL_HapticEffect *data)
// void SDL_free(void *mem)

// 合计 50 个函数
